<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\src\MyRecipeBook.Communication\MyRecipeBook.Communication.csproj"/>
        <ProjectReference Include="..\..\src\MyRecipeBook.Domain\MyRecipeBook.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Bogus"/>
        <PackageReference Include="Moq"/>
    </ItemGroup>

</Project>
